/**
 * A remote, drawn. The only place in this application that puts an SVG string into the DOM.
 *
 * `toSvg` returns markup rather than elements, so somebody has to hand it to the browser. Doing that
 * in one component is the whole point: two places that inject a drawing are two places that decide
 * its size, its detail level and its accessibility, and they drift. Views ask for a drawing and get
 * a picture.
 *
 * `dangerouslySetInnerHTML` is safe here in the way the name asks about: the markup is generated by a
 * library in this workspace from a table of numbers, not received from anywhere. No config, no
 * network and no user input reaches it.
 *
 * **The drawing carries no size**, only a viewBox, so a bare one fills whatever it is in. The
 * stylesheet beside this file gives it a height and lets the width follow, which is what makes a
 * Harmony 525 and a Harmony One line up: every model is drawn to the same case height on purpose.
 */
import { useMemo } from 'react';

import { toSvg, type Model } from '@harmony/silhouettes';

import { DRAWING_DETAIL } from '../catalogue.ts';
import classes from './Silhouette.module.scss';

interface SilhouetteProps {
  readonly drawing: Model;
  /** `tile` for a list, `full` for a model on its own. */
  readonly detail?: keyof typeof DRAWING_DETAIL;
  readonly className?: string | undefined;
}

export function Silhouette({ drawing, detail = 'tile', className }: SilhouetteProps) {
  // Memoised because a drawing is tens of kilobytes of markup and a parent redraws for its own
  // reasons. The sibling repository has hit the cost of a reader called inside a loop twice; this is
  // the same shape with a browser attached.
  const markup = useMemo(
    () => toSvg(drawing, { layers: DRAWING_DETAIL[detail] }),
    [drawing, detail],
  );

  return (
    <div
      className={className === undefined ? classes.frame : `${classes.frame} ${className}`}
      // The drawing states its own accessible name through `role="img"` and a title, so nothing is
      // added here that would say it twice.
      dangerouslySetInnerHTML={{ __html: markup }}
    />
  );
}
